# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - mywebapp-hamza

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_e890bcf62f3d4aeaad5fc96d29a768f2 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e9f0804b5f8047808c661c5711543000 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_e890bcf62f3d4aeaad5fc96d29a768f2 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mywebapp-hamza'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5325e4376d104f5fa469b7d5230815b8 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_e890bcf62f3d4aeaad5fc96d29a768f2 }}/appsvc/staticsite:${{ github.sha }}'